config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :carts
  root 'store#index', as: 'store_index'
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy

    def add_product(product)
        current_item = line_items.find_by(product_id: product.id)
        if current_item
            current_item.quantity += 1
        else
            current_item = line_items.build(product_id: product.id)
        end
        current_item
    end

    def total_price
        line_items.to_a.sum{|item| item.total_price}
    end


end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item


    validates :title, :description, :image_url, :price, presence: true 
    validates :price, numericality: { greater_than_or_equal_to: 10 }
    validates :title, uniqueness: true
    validates :image_url, format: {
        with: /\w+\.(jpg|png)\z/i,
        message: "debe ser una imágen JPG o PNG "
      }

      private

      def ensure_not_referenced_by_any_line_item
        unless line.items.empty?
          errors.add(:base, 'Line Items present')
            throw :abort
        end
      end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit,  :update, :destroy ]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  # GET /carts or /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1 or /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts or /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created." }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1 or /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated." }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1 or /carts/1.json
  def destroy
    @cart.destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id]=nil
    respond_to do |format|
      format.html { redirect_to store_index_url, notice: "Su carro está actualmente vacío" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end

    def invalid_cart
      logger.error "Intenta accesar Nº carro inválido #{params[:id]}"
      redirect_to store_index_url, notice: 'Carro inválido'
    end

end

app/controllers/concerns/current_cart.rb
module CurrentCart
    private
    def set_cart
        @cart = Cart.find(session[:cart_id])
        rescue ActiveRecord::RecordNotFound
            @cart = Cart.create
            session[:cart_id] = @cart.id
        end
    end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only:[:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items or /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1 or /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items or /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url}
        format.js {@current_item = @line_item}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1 or /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: "Line item was successfully updated." }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1 or /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: "Line item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
include CurrentCart
before_action :set_cart
  def index
    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.erb
<article>
    <% if notice %>
        <aside id="notice"><%= notice %></aside>
    <% end %>

    <h2>Su Carro Telecompras</h2>
    <table>
            <%= render(@cart.line_items) %>
            <tfoot>
                <tr>
                    <th colspan="2">Total:</th>
                    <td class="price"><%= number_to_currency(@cart.total_price) %></td>
                </tr>
            </tfoot>
    </table>
        <%= button_to 'Carro vacío', @cart, method: :delete, data: {confirm: '¿Está usted seguro?'} %>
    
</article>

app/views/carts/_form.html.erb
<%= form_with(model: cart) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= render @cart %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Telecompras tienda online</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="main">
    <%= image_tag 'logo.svg', alt: 'Telecompras' %>
    <h1><%= @page_title %></h1>
  </header>
  <section class="content">
    <nav class="side_nav">
    <% if @cart %>
      <div id="cart" class="carts">
        <%= render @cart %>
      </div>
    <% end %>
      <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/questions">Preguntas</a></li>
        <li><a href="/news">Novedades</a></li>
        <li><a href="/contact">Contacto</a></li>
      </ul>
    </nav>

  <main class='<%= controller.controller_name %>'>
    <%= yield %>
  </main>
  </section>
  </body>
</html>

app/views/line_items/_form.html.erb
<%= form_with(model: line_item) do |form| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
        <% line_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :cart_id %>
    <%= form.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr class="line-item-highlight">
<% else %>
<tr>
<% end %>
        <td class="quantity"><%= line_item.quantity %></td>
        <td><%= line_item.product.title %></td>
        <td class="price"><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/create.js.erb
cart = document.getElementById("cart")
cart.innerHTML = "<%= j render(@cart) %>"

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2>Hay error(es) que impide(n) que este producto sea guardado:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Nombre" %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label "Descripción" %>
    <%= form.text_area :description, rows:10, cols:60 %>
  </div>

  <div class="field">
    <%= form.label "Ruta de la Imagen" %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label "Precio" %>
    <%= form.text_field :price %>
  </div>

  <% if current_page?(new_product_path) %>
    <div class="actions">
      <%= form.submit "Crear Producto" %>
    </div>
  <% else %>
    <div class="actions">
    <%= form.submit "Editar Producto" %>
  </div>
  <% end %>
<% end %>

app/views/products/edit.html.erb
<h1>Edición de Producto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Mostrar', @product %> |
<%= link_to 'Atrás', products_path %>

app/views/products/index.html.erb
<% if notice %> 
<aside id='notice><%= notice %></aside>
<% end %>

<h1>Productos</h1>

<table>
  <tfoot>
    <tr>
      <td colspan="3">
        <%= link_to 'Nuevo producto', new_product_path %>
      </td>
    </tr>
  </tfoot>

  <tbody>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd','list_line_even') %>">
      
      <td class="image">
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>

      <td class="description">
        <h1><%= product.title %></h1>
        <p>
          <%= truncate(strip_tags(product.description), length: 80) %> 
        </p>

      </td>

      <td class=actions">
        <ul>
          <li><%= link_to "Ver", product %></li>
          <li><%= link_to "Editar", edit_product_path(product) %></li>
          <li><%= link_to "Eliminar", product, method: :delete, data: { confirm: 'Está seguro'} %></li>
        </ul>
      </td>
    </tr>
  <% end %>
</tbody>
</table>


      

app/views/products/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form', product: @product %>

<%= link_to 'Atrás', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Producto:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Ruta imagen:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Editar', edit_product_path(@product) %> |
<%= link_to 'Atrás', products_path %>

app/views/store/index.html.erb
<% if notice %>
    <aside id="notice"><%= notice %></aside>
<% end %>

<h1>Catálogo Telecompras</h1>

<ul class="catalog">
    <% cache @products do %>
            <% @products.each do |product| %>
                <% cache product do %>
                    <li>
                        <%= image_tag(product.image_url) %>
                        <h2><%= product.title %></h2>
                        <p>
                            <%= sanitize(product.description) %>
                        </p>
                        <div class="price">
                            <%= number_to_currency(product.price) %>
                            <%= button_to "Agregar al Carro", line_items_path(product_id: product), remote: true %>
                        </div>
                    </li>
                <%end %>
            <% end %>
    <% end %>
</ul>